openapi: 3.1.0
info:
  title: UAC
  description: >-
    The UAC API is an authorization service which determines access to
    predefined resources through the use of Policy-Based validations and
    restrictions.
  version: 1.0.0
schemes:
  - http
  - https
  - ws
  - wss
paths:
  /auth:
    $ref: docs/auth.yml
  /erf-form:
    $ref: docs/erf-form.yml
  /hbs-samples:
    $ref: docs/hbs-samples.yml
  /new-applicant:
    $ref: docs/new-applicant.yml
  /notification:
    $ref: docs/notification.yml
  /admin/object-authority:
    $ref: docs/admin/object-authority.yml
  /otp:
    $ref: docs/otp.yml
  /admin/policy-authority:
    $ref: docs/admin/policy-authority.yml
  /registry:
    $ref: docs/registry.yml
  /sms-attachment:
    $ref: docs/sms-attachment.yml
  /sms-education:
    $ref: docs/sms-education.yml
  /sms-eligibility:
    $ref: docs/sms-eligibility.yml
  /sms-endorsement:
    $ref: docs/sms-endorsement.yml
  /sms-experience:
    $ref: docs/sms-experience.yml
  /sms-leadership:
    $ref: docs/sms-leadership.yml
  /sms-ma-units:
    $ref: docs/sms-ma-units.yml
  /sms-position:
    $ref: docs/sms-position.yml
  /sms-rating:
    $ref: docs/sms-rating.yml
  /sms-rd:
    $ref: docs/sms-rd.yml
  /sms-roles:
    $ref: docs/sms-roles.yml
  /sms-salary-grade:
    $ref: docs/sms-salary-grade.yml
  /sms-school:
    $ref: docs/sms-school.yml
  /sms-sdo:
    $ref: docs/sms-sdo.yml
  /admin/subject-authority:
    $ref: docs/admin/subject-authority.yml
  /user-uploads:
    $ref: docs/user-uploads.yml
  /user:
    $ref: docs/user.yml
